services:
  springboot-app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/neighborhelp
      - SPRING_DATASOURCE_USERNAME=bobby
      - SPRING_DATASOURCE_PASSWORD=Futbol2005@
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql-db
    networks:
      - app-network

  mysql-db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=neighborhelp
      - MYSQL_USER=bobby
      - MYSQL_PASSWORD=Futbol2005@
      - MYSQL_ROOT_PASSWORD=Futbol2005@
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123" ]
      timeout: 30s
      retries: 10
      start_period: 60s
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge