app = 'neighborunion-backend'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  # AGREGAR ESTO - Health checks
  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    method = "GET"
    path = "/actuator/health"
    
  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    method = "GET"
    path = "/health"

[vm]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

# AGREGAR ESTO - Variables de entorno
[env]
  SPRING_PROFILES_ACTIVE = "prod"
  JAVA_OPTS = "-Xmx512m -Xms256m"
